name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.27'

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Clear Config Cache
        run: php artisan config:cache

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Clear Cache
        run: php artisan cache:clear




